### ISSUE TITLE
DO you provide update on purchase

### ISSUE THREAD

**Issue by effectuall** [codeartisanlab/Learning-Managment-System-LMS-in-Django-with-Reactjs#1]

**Comment by codeartisanlab** [comment]
Thank you for your response
I will let you know about the timing for demo today by this evening

**Comment by codeartisanlab** [comment]
Hi, Thank you for your patience.
Can we schedule demo of lms for tommarow at 10 am

**Comment by effectuall** [comment]
Hi,
10.00 AM Qatar Time I am available.

**Comment by codeartisanlab** [comment]
Ok 👍

**Comment by effectuall** [comment]
Thursday, November 21 · 10:00 – 11:00am
Time zone: Asia/Qatar
Google Meet joining info
Video call link: https://meet.google.com/bip-kezx-cfc

**Comment by codeartisanlab** [comment]
Thank you so much
Sorry, can we please reschedule at 5- 6 PM 🙏

**Comment by effectuall** [comment]
Re: [codeartisanlab/Learning-Managment-System-LMS-in-Django-with-Reactjs]
DO you provide update on purchase (Issue #1)
Thursday, November 21 · 5:00 – 6:00pm
Time zone: Asia/Qatar
Google Meet joining info
Video call link: https://meet.google.com/bip-kezx-cfc

Can you share your email to add to the google calendar invite

**Comment by codeartisanlab** [comment]
Thank you 🙏

**Comment by codeartisanlab** [comment]
Hi, can we connect now

**Comment by effectuall** [comment]
Yes, I am ready.

**Comment by codeartisanlab** [comment]
This is a sample screenshot of my github code and you can see how it is if
you know about github.
I am not saying to purchase my code but according to our discussion it
seems that you are underestimated my time and discussion and also it seems
that are not interested or something, i don't know
I am sending this screenshots to you just for your reference
[image: image.png]
[image: image.png]
 For better understanding, you can watch the videos

**Comment by effectuall** [comment]
No image added

**Comment by codeartisanlab** [comment]
for images, check you email
in github, images are not showing
